In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
data = pd.read_csv('complete_train.csv')

In [2]:
data.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,h1n1_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0

In [3]:
X  = data.iloc[:,0:36].values
Y1 = data.iloc[:,36].values
Y2 = data.iloc[:,37].values

In [4]:
from sklearn.impute import SimpleImputer

In [12]:
data.isnull().sum()

respondent_id                      0
h1n1_concern                      92
h1n1_knowledge                   116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_h1n1                2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_h1n1_vacc_effective      391
opinion_h1n1_risk                388
opinion_h1n1_sick_from_vacc      395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
rent_or_own                     2042
employment_status               1463
hhs_geo_region                     0
census_msa                         0
household_adults                 249
household_children               249
employment_industry            13330
employment_occupation          13470
h1n1_vaccine                       0
seasonal_vaccine                   0
dtype: int64

In [13]:
del data['employment_industry']
del data['employment_occupation']
del data['health_insurance']

In [14]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                     92
h1n1_knowledge                  116
behavioral_antiviral_meds        71
behavioral_avoidance            208
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [18]:
df = pd.DataFrame()
df["h1n1_concern"] = data["h1n1_concern"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"h1n1_concern"})
data["h1n1_concern"] = df1["h1n1_concern"]

In [19]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                  116
behavioral_antiviral_meds        71
behavioral_avoidance            208
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [20]:
df = pd.DataFrame()
df["h1n1_knowledge"] = data["h1n1_knowledge"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"h1n1_knowledge"})
data["h1n1_knowledge"] = df1["h1n1_knowledge"]

In [21]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds        71
behavioral_avoidance            208
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [22]:
df = pd.DataFrame()
df["behavioral_antiviral_meds"] = data["behavioral_antiviral_meds"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"behavioral_antiviral_meds"})
data["behavioral_antiviral_meds"] = df1["behavioral_antiviral_meds"]

In [23]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds         0
behavioral_avoidance            208
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [24]:
df = pd.DataFrame()
df["behavioral_avoidance"] = data["behavioral_avoidance"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"behavioral_avoidance"})
data["behavioral_avoidance"] = df1["behavioral_avoidance"]

In [25]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds         0
behavioral_avoidance              0
behavioral_face_mask             19
behavioral_wash_hands            42
behavioral_large_gatherings      87
behavioral_outside_home          82
behavioral_touch_face           128
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [26]:
df = pd.DataFrame()
df["behavioral_face_mask"] = data["behavioral_face_mask"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"behavioral_face_mask"})
data["behavioral_face_mask"] = df1["behavioral_face_mask"]

In [27]:
df = pd.DataFrame()
df["behavioral_wash_hands"] = data["behavioral_wash_hands"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"behavioral_wash_hands"})
data["behavioral_wash_hands"] = df1["behavioral_wash_hands"]

In [28]:
df = pd.DataFrame()
df["behavioral_large_gatherings"] = data["behavioral_large_gatherings"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"behavioral_large_gatherings"})
data["behavioral_large_gatherings"] = df1["behavioral_large_gatherings"]

In [29]:
df = pd.DataFrame()
df["behavioral_outside_home"] = data["behavioral_outside_home"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"behavioral_outside_home"})
data["behavioral_outside_home"] = df1["behavioral_outside_home"]

In [30]:
df = pd.DataFrame()
df["behavioral_touch_face"] = data["behavioral_touch_face"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"behavioral_touch_face"})
data["behavioral_touch_face"] = df1["behavioral_touch_face"]

In [31]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds         0
behavioral_avoidance              0
behavioral_face_mask              0
behavioral_wash_hands             0
behavioral_large_gatherings       0
behavioral_outside_home           0
behavioral_touch_face             0
doctor_recc_h1n1               2160
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [32]:
data.columns

Index(['respondent_id', 'h1n1_concern', 'h1n1_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
       'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'hhs_geo_region', 'census_msa',
       'household_adults', 'household_children', 'h1n1_vaccine',
       'seasonal_vaccine'],
      dtype='object')

In [36]:
from sklearn.impute import KNNImputer
df = pd.DataFrame(data.h1n1_concern)
df["h1n1_knowledge"] = data.h1n1_knowledge
df["behavioral_antiviral_meds"] = data.behavioral_antiviral_meds
df["behavioral_avoidance"] = data.behavioral_avoidance
df["behavioral_face_mask"] = data.behavioral_face_mask
df["behavioral_wash_hands"] = data.behavioral_wash_hands
df["behavioral_large_gatherings"] = data.behavioral_large_gatherings
df["behavioral_outside_home"] = data.behavioral_outside_home
df["behavioral_touch_face"] = data.behavioral_touch_face
df["doctor_recc_h1n1"] = data.doctor_recc_h1n1

In [37]:
df.head()

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [38]:
imputer = KNNImputer(n_neighbors=9)
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)

df1.head()

     0    1    2    3    4    5    6    7    8         9
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.000000
1  3.0  2.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.000000
2  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.111111
3  1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.000000
4  2.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.000000

In [39]:
df1 = df1.rename(columns={9:"doctor_recc_h1n1"})

In [40]:
df1.head()

     0    1    2    3    4    5    6    7    8  doctor_recc_h1n1
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0          0.000000
1  3.0  2.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0          0.000000
2  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0          0.111111
3  1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0          0.000000
4  2.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0          0.000000

In [41]:
data["doctor_recc_h1n1"] = df1["doctor_recc_h1n1"]

In [42]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds         0
behavioral_avoidance              0
behavioral_face_mask              0
behavioral_wash_hands             0
behavioral_large_gatherings       0
behavioral_outside_home           0
behavioral_touch_face             0
doctor_recc_h1n1                  0
doctor_recc_seasonal           2160
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [44]:
from sklearn.impute import KNNImputer
df = pd.DataFrame(data.behavioral_antiviral_meds)
df["behavioral_avoidance"] = data.behavioral_avoidance
df["behavioral_face_mask"] = data.behavioral_face_mask
df["behavioral_wash_hands"] = data.behavioral_wash_hands
df["behavioral_large_gatherings"] = data.behavioral_large_gatherings
df["behavioral_outside_home"] = data.behavioral_outside_home
df["behavioral_touch_face"] = data.behavioral_touch_face
df["doctor_recc_seasonal"] = data.doctor_recc_seasonal

In [45]:
df.head()

,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_seasonal
0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
3,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
4,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [46]:
imputer = KNNImputer(n_neighbors=9)
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)

df1.head()

     0    1    2    3    4    5    6         7
0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.000000
1  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.000000
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.333333
3  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.000000
4  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.000000

In [47]:
df1 = df1.rename(columns={7:"doctor_recc_seasonal"})

In [48]:
data["doctor_recc_seasonal"] = df1["doctor_recc_seasonal"]

In [49]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds         0
behavioral_avoidance              0
behavioral_face_mask              0
behavioral_wash_hands             0
behavioral_large_gatherings       0
behavioral_outside_home           0
behavioral_touch_face             0
doctor_recc_h1n1                  0
doctor_recc_seasonal              0
chronic_med_condition           971
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [50]:
from sklearn.impute import KNNImputer
df = pd.DataFrame(data.behavioral_antiviral_meds)
df["behavioral_avoidance"] = data.behavioral_avoidance
df["behavioral_face_mask"] = data.behavioral_face_mask
df["behavioral_wash_hands"] = data.behavioral_wash_hands
df["behavioral_large_gatherings"] = data.behavioral_large_gatherings
df["behavioral_outside_home"] = data.behavioral_outside_home
df["behavioral_touch_face"] = data.behavioral_touch_face
df["chronic_med_condition"] = data.chronic_med_condition

In [53]:
df.head()

,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,chronic_med_condition
0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
4,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [54]:
imputer = KNNImputer(n_neighbors=9)
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)

df1.head()

     0    1    2    3    4    5    6    7
0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0
1  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
3  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0
4  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0

In [55]:
df1 = df1.rename(columns={7:"chronic_med_condition"})

In [56]:
df1.head()

     0    1    2    3    4    5    6  chronic_med_condition
0  0.0  0.0  0.0  0.0  0.0  1.0  1.0                    0.0
1  0.0  1.0  0.0  1.0  0.0  1.0  1.0                    0.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0                    1.0
3  0.0  1.0  0.0  1.0  1.0  0.0  0.0                    1.0
4  0.0  1.0  0.0  1.0  1.0  0.0  1.0                    0.0

In [57]:
data["chronic_med_condition"] = df1["chronic_med_condition"]

In [58]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds         0
behavioral_avoidance              0
behavioral_face_mask              0
behavioral_wash_hands             0
behavioral_large_gatherings       0
behavioral_outside_home           0
behavioral_touch_face             0
doctor_recc_h1n1                  0
doctor_recc_seasonal              0
chronic_med_condition             0
child_under_6_months            820
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [59]:
df = pd.DataFrame()
df["child_under_6_months"] = data["child_under_6_months"]
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
df_filled = imputer.fit_transform(df)
df1 = pd.DataFrame(df_filled)
df1 = df1.rename(columns={0:"child_under_6_months"})
data["child_under_6_months"] = df1["child_under_6_months"]

In [60]:
data.isnull().sum()

respondent_id                     0
h1n1_concern                      0
h1n1_knowledge                    0
behavioral_antiviral_meds         0
behavioral_avoidance              0
behavioral_face_mask              0
behavioral_wash_hands             0
behavioral_large_gatherings       0
behavioral_outside_home           0
behavioral_touch_face             0
doctor_recc_h1n1                  0
doctor_recc_seasonal              0
chronic_med_condition             0
child_under_6_months              0
health_worker                   804
opinion_h1n1_vacc_effective     391
opinion_h1n1_risk               388
opinion_h1n1_sick_from_vacc     395
opinion_seas_vacc_effective     462
opinion_seas_risk               514
opinion_seas_sick_from_vacc     537
age_group                         0
education                      1407
race                              0
sex                               0
income_poverty                 4423
marital_status                 1408
rent_or_own                    2042
employment_status              1463
hhs_geo_region                    0
census_msa                        0
household_adults                249
household_children              249
h1n1_vaccine                      0
seasonal_vaccine                  0
dtype: int64

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 35 columns):
respondent_id                  26707 non-null int64
h1n1_concern                   26707 non-null float64
h1n1_knowledge                 26707 non-null float64
behavioral_antiviral_meds      26707 non-null float64
behavioral_avoidance           26707 non-null float64
behavioral_face_mask           26707 non-null float64
behavioral_wash_hands          26707 non-null float64
behavioral_large_gatherings    26707 non-null float64
behavioral_outside_home        26707 non-null float64
behavioral_touch_face          26707 non-null float64
doctor_recc_h1n1               26707 non-null float64
doctor_recc_seasonal           26707 non-null float64
chronic_med_condition          26707 non-null float64
child_under_6_months           26707 non-null float64
health_worker                  25903 non-null float64
opinion_h1n1_vacc_effective    26316 non-null float64
opinion_h1n1_risk              26319 non-null float64
opinion_h1n1_sick_from_vacc    26312 non-null float64
opinion_seas_vacc_effective    26245 non-null float64
opinion_seas_risk              26193 non-null float64
opinion_seas_sick_from_vacc    26170 non-null float64
age_group                      26707 non-null object
education                      25300 non-null object
race                           26707 non-null object
sex                            26707 non-null object
income_poverty                 22284 non-null object
marital_status                 25299 non-null object
rent_or_own                    24665 non-null object
employment_status              25244 non-null object
hhs_geo_region                 26707 non-null object
census_msa                     26707 non-null object
household_adults               26458 non-null float64
household_children             26458 non-null float64
h1n1_vaccine                   26707 non-null int64
seasonal_vaccine               26707 non-null int64
dtypes: float64(22), int64(3), object(10)
memory usage: 7.1+ MB

In [118]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
X = data.iloc[:,0:35].values

In [119]:
df = pd.DataFrame(X)

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 34 columns):
0     26707 non-null object
1     26707 non-null object
2     26707 non-null object
3     26707 non-null object
4     26707 non-null object
5     26707 non-null object
6     26707 non-null object
7     26707 non-null object
8     26707 non-null object
9     26707 non-null object
10    26707 non-null object
11    26707 non-null object
12    26707 non-null object
13    26707 non-null object
14    26707 non-null object
15    26316 non-null object
16    26319 non-null object
17    26312 non-null object
18    26245 non-null object
19    26193 non-null object
20    26170 non-null object
21    26707 non-null object
22    26707 non-null object
23    26707 non-null object
24    26707 non-null object
25    26707 non-null object
26    26707 non-null object
27    26707 non-null object
28    26707 non-null object
29    26707 non-null object
30    26707 non-null object
31    26707 non-null object
32    26458 non-null object
33    26707 non-null object
dtypes: object(34)
memory usage: 6.9+ MB

In [108]:
X[:,21]=labelencoder_x.fit_transform(X[:,21])
X[:,22]=labelencoder_x.fit_transform(X[:,22])
X[:,23]=labelencoder_x.fit_transform(X[:,23])
X[:,24]=labelencoder_x.fit_transform(X[:,24])
X[:,25]=labelencoder_x.fit_transform(X[:,25])
X[:,26]=labelencoder_x.fit_transform(X[:,26])
X[:,27]=labelencoder_x.fit_transform(X[:,27])
X[:,28]=labelencoder_x.fit_transform(X[:,28])
X[:,29]=labelencoder_x.fit_transform(X[:,29])
X[:,30]=labelencoder_x.fit_transform(X[:,30])

In [109]:
X[0]

array([0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 3.0, 1.0, 2.0, 2.0, 1.0, 2.0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       0.0, 0], dtype=object)

In [110]:
df = pd.DataFrame(X)

In [111]:
df.head()

  0  1  2  3  4  5  6  7  8  9   ... 24 25 26 27 28 29 30 31 32 33
0  0  1  0  0  0  0  0  0  1  1  ...  3  3  3  3  3  3  3  3  0  0
1  1  3  2  0  1  0  1  0  1  1  ...  1  1  1  1  1  1  1  1  0  0
2  2  1  1  0  1  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
3  3  1  1  0  1  0  1  1  0  0  ...  4  4  4  4  4  4  4  4  0  0
4  4  2  1  0  1  0  1  1  0  1  ...  2  2  2  2  2  2  2  2  0  0

[5 rows x 34 columns]

In [112]:
data.columns

Index(['child_under_6_months', 'h1n1_concern', 'h1n1_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
       'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'hhs_geo_region', 'census_msa',
       'household_adults', 'household_children', 'h1n1_vaccine'],
      dtype='object')

In [85]:
df = df.rename(columns={0:"respondent_id"})
df = df.rename(columns={1:"h1n1_concern"})
df = df.rename(columns={2:"h1n1_knowledge"})
df = df.rename(columns={3:"behavioral_antiviral_meds"})
df = df.rename(columns={4:"behavioral_avoidance"})
df = df.rename(columns={5:"behavioral_face_mask"})
df = df.rename(columns={6:"behavioral_wash_hands"})
df = df.rename(columns={7:"behavioral_large_gatherings"})
df = df.rename(columns={8:"behavioral_outside_home"})
df = df.rename(columns={9:"behavioral_touch_face"})
df = df.rename(columns={10:"doctor_recc_h1n1"})
df = df.rename(columns={11:"doctor_recc_seasonal"})
df = df.rename(columns={12:"chronic_med_condition"})
df = df.rename(columns={13:"child_under_6_months"})
df = df.rename(columns={14:"health_worker"})
df = df.rename(columns={15:"opinion_h1n1_vacc_effective"})
df = df.rename(columns={16:"opinion_h1n1_risk"})
df = df.rename(columns={17:"opinion_h1n1_sick_from_vacc"})
df = df.rename(columns={18:"opinion_seas_vacc_effective"})
df = df.rename(columns={19:"opinion_seas_risk"})
df = df.rename(columns={20:"opinion_seas_sick_from_vacc"})
df = df.rename(columns={21:"age_group"})
df = df.rename(columns={22:"education"})
df = df.rename(columns={23:"race"})
df = df.rename(columns={24:"sex"})
df = df.rename(columns={25:"income_poverty"})
df = df.rename(columns={26:"marital_status"})
df = df.rename(columns={27:"rent_or_own"})
df = df.rename(columns={28:"employment_status"})
df = df.rename(columns={29:"hhs_geo_region"})
df = df.rename(columns={30:"census_msa"})
df = df.rename(columns={31:"household_adults"})
df = df.rename(columns={32:"household_children"})
df = df.rename(columns={33:"h1n1_vaccine"})
df = df.rename(columns={34:"seasonal_vaccine"})

In [86]:
df.head()

,child_under_6_months,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,sex,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,h1n1_vaccine
0,0,1,0,0,0,0,0,0,1,1,...,3,3,3,3,3,3,3,3,0,0
1,1,3,2,0,1,0,1,0,1,1,...,1,1,1,1,1,1,1,1,0,0
2,2,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,1,1,0,1,0,1,1,0,0,...,4,4,4,4,4,4,4,4,0,0
4,4,2,1,0,1,0,1,1,0,1,...,2,2,2,2,2,2,2,2,0,0

In [87]:
data = df

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 34 columns):
child_under_6_months           26707 non-null object
h1n1_concern                   26707 non-null object
h1n1_knowledge                 26707 non-null object
behavioral_antiviral_meds      26707 non-null object
behavioral_avoidance           26707 non-null object
behavioral_face_mask           26707 non-null object
behavioral_wash_hands          26707 non-null object
behavioral_large_gatherings    26707 non-null object
behavioral_outside_home        26707 non-null object
behavioral_touch_face          26707 non-null object
doctor_recc_h1n1               26707 non-null object
doctor_recc_seasonal           26707 non-null object
chronic_med_condition          26707 non-null object
child_under_6_months           26707 non-null object
health_worker                  25903 non-null object
opinion_h1n1_vacc_effective    26316 non-null object
opinion_h1n1_risk              26319 non-null object
opinion_h1n1_sick_from_vacc    26312 non-null object
opinion_seas_vacc_effective    26245 non-null object
opinion_seas_risk              26193 non-null object
opinion_seas_sick_from_vacc    26170 non-null object
age_group                      26707 non-null object
education                      26707 non-null object
race                           26707 non-null object
sex                            26707 non-null object
income_poverty                 26707 non-null object
marital_status                 26707 non-null object
rent_or_own                    26707 non-null object
employment_status              26707 non-null object
hhs_geo_region                 26707 non-null object
census_msa                     26707 non-null object
household_adults               26707 non-null object
household_children             26458 non-null object
h1n1_vaccine                   26707 non-null object
dtypes: object(34)
memory usage: 6.9+ MB

In [89]:
data.isnull().sum()

child_under_6_months             0
h1n1_concern                     0
h1n1_knowledge                   0
behavioral_antiviral_meds        0
behavioral_avoidance             0
behavioral_face_mask             0
behavioral_wash_hands            0
behavioral_large_gatherings      0
behavioral_outside_home          0
behavioral_touch_face            0
doctor_recc_h1n1                 0
doctor_recc_seasonal             0
chronic_med_condition            0
child_under_6_months             0
health_worker                  804
opinion_h1n1_vacc_effective    391
opinion_h1n1_risk              388
opinion_h1n1_sick_from_vacc    395
opinion_seas_vacc_effective    462
opinion_seas_risk              514
opinion_seas_sick_from_vacc    537
age_group                        0
education                        0
race                             0
sex                              0
income_poverty                   0
marital_status                   0
rent_or_own                      0
employment_status                0
hhs_geo_region                   0
census_msa                       0
household_adults                 0
household_children             249
h1n1_vaccine                     0
dtype: int64

In [95]:
from sklearn.impute import KNNImputer
df = pd.DataFrame(data.sex)
df["education"] = data.education
df["age_group"] = data.age_group
df["race"] = data.race
df["employment_status"] = data.employment_status
df["health_worker"] = data.health_worker

In [96]:
imputer = KNNImputer(n_neighbors=6)
df_filled = imputer.fit_transform(df)
df = pd.DataFrame(df_filled)
df.head()

     0    1    2    3    4    5
0  3.0  3.0  3.0  3.0  3.0  0.0
1  1.0  1.0  1.0  1.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  4.0  4.0  4.0  4.0  4.0  0.0
4  2.0  2.0  2.0  2.0  2.0  0.0

In [97]:
df = df.rename(columns={5:"health_worker"})

In [98]:
data["health_worker"] = df["health_worker"]

In [99]:
data.isnull().sum()

child_under_6_months             0
h1n1_concern                     0
h1n1_knowledge                   0
behavioral_antiviral_meds        0
behavioral_avoidance             0
behavioral_face_mask             0
behavioral_wash_hands            0
behavioral_large_gatherings      0
behavioral_outside_home          0
behavioral_touch_face            0
doctor_recc_h1n1                 0
doctor_recc_seasonal             0
chronic_med_condition            0
child_under_6_months             0
health_worker                    0
opinion_h1n1_vacc_effective    391
opinion_h1n1_risk              388
opinion_h1n1_sick_from_vacc    395
opinion_seas_vacc_effective    462
opinion_seas_risk              514
opinion_seas_sick_from_vacc    537
age_group                        0
education                        0
race                             0
sex                              0
income_poverty                   0
marital_status                   0
rent_or_own                      0
employment_status                0
hhs_geo_region                   0
census_msa                       0
household_adults                 0
household_children             249
h1n1_vaccine                     0
dtype: int64

In [ ]:
from sklearn.impute import KNNImputer
df = pd.DataFrame(data.sex)
df["education"] = data.education
df["age_group"] = data.age_group
df["race"] = data.race
df["employment_status"] = data.employment_status
df["health_worker"] = data.health_worker